steps:
  - name: 'docker'
    args:
      - 'buildx'
      - 'create'
      - '--name'
      - 'mybuilder'
      - '--use'
  - name: 'docker'
    args: 
      - 'buildx'
      - 'build'
      - '--platform'
      - 'linux/arm64,linux/amd64'
      - '-t'
      - 'us-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/ping-demo:$SHORT_SHA'
      - '-t'
      - 'us-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/ping-demo:latest'
      - '--push'
      - '.'
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=manifests/ping-demo-default.yaml
      - --image=us-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/ping-demo:$SHORT_SHA
      - --cluster=${_CLUSTER_NAME}
      - --location=$LOCATION
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=manifests/ping-demo-balanced.yaml
      - --image=us-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/ping-demo:$SHORT_SHA
      - --cluster=${_CLUSTER_NAME}
      - --location=$LOCATION
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=manifests/ping-demo-scale-out-amd64.yaml
      - --image=us-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/ping-demo:$SHORT_SHA
      - --cluster=${_CLUSTER_NAME}
      - --location=$LOCATION
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=manifests/ping-demo-scale-out-arm.yaml
      - --image=us-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/ping-demo:$SHORT_SHA
      - --cluster=${_CLUSTER_NAME}
      - --location=$LOCATION
options:
  requestedVerifyOption: VERIFIED
substitutions:
  _CLUSTER_NAME: ap-security-demo
  _REPO_NAME: gke-demos
