apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: my-gke-demo-app-1
description: main application pipeline
serialPipeline:
  stages:
  - targetId: qsdev
    profiles: []
  - targetId: qsprod
    profiles: []
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: qsdev
description: prod cluster
gke:
  cluster: projects/gke-demos-345619/locations/us-central1/clusters/ap-demo1
