steps:
  - name: 'docker'
    args:
      - 'buildx'
      - 'create'
      - '--name'
      - 'mybuilder'
      - '--use'
  - name: 'docker'
    args: 
      - 'buildx'
      - 'build'
      - '--platform'
      - 'linux/arm64,linux/amd64'
      - '-t'
      - 'us-docker.pkg.dev/gari-test/cloudonair/ping-demo:$SHORT_SHA'
      - '-t'
      - 'us-docker.pkg.dev/gari-test/cloudonair/ping-demo:latest'
      - '--push'
      - '.'
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=manifests/ping-demo-default.yaml
      - --image=us-docker.pkg.dev/gari-test/cloudonair/ping-demo:$SHORT_SHA
      - --location=us-central1
      - --cluster=cloudonair-demo
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=manifests/ping-demo-balanced.yaml
      - --image=us-docker.pkg.dev/gari-test/cloudonair/ping-demo:$SHORT_SHA
      - --location=us-central1
      - --cluster=cloudonair-demo
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=manifests/ping-demo-scale-out-amd64.yaml
      - --image=us-docker.pkg.dev/gari-test/cloudonair/ping-demo:$SHORT_SHA
      - --location=us-central1
      - --cluster=cloudonair-demo
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=manifests/ping-demo-scale-out-arm.yaml
      - --image=us-docker.pkg.dev/gari-test/cloudonair/ping-demo:$SHORT_SHA
      - --location=us-central1
      - --cluster=cloudonair-demo