steps:
  - name: 'docker'
    args:
      - 'buildx'
      - 'create'
      - '--name'
      - 'mybuilder'
      - '--use'
  - name: 'docker'
    args: 
      - 'buildx'
      - 'build'
      - '--platform'
      - 'linux/arm64,linux/amd64'
      - '-t'
      - 'us-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/ping-demo:$SHORT_SHA'
      - '-t'
      - 'us-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/ping-demo:latest'
      - '.'
images:
  - us-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/ping-demo:$SHORT_SHA
  - us-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/ping-demo:latest
options:
  requestedVerifyOption: 'VERIFIED'
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _CLUSTER_NAME: ap-security-demo
  _REPO_NAME: gke-demos
