apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: ping-demo
description: main application pipeline
serialPipeline:
  stages:
  - targetId: prod
    profiles: []
---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: prod cluster
gke:
  cluster: projects/gke-demos-345619/locations/us-central1/clusters/ap-demo1
