apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ping-demo
  name: ping-demo-balanced
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-demo
  template:
    metadata:
      labels:
        app: ping-demo
    spec:
      nodeSelector:
        cloud.google.com/compute-class: Balanced
        kubernetes.io/arch: amd64
      containers:
      - image: us-docker.pkg.dev/gke-demos-345619/compute-classes/ping-demo@sha256:118fbf48b910029b92c2f9901e7ccf014591c555ed7c567a8058d66500b088f3
        name: ping-demo-balanced