apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ping-demo
  name: ping-demo-default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-demo
  template:
    metadata:
      labels:
        app: ping-demo
    spec:
      containers:
      - image: us-docker.pkg.dev/gke-demos-345619/compute-classes/ping-demo@sha256:6e757daccc68453d1f5837fa625172f7a059a72e70306af835124b175df7fb55
        name: ping-demo-default
        resources:
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
          limits:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi