apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ping-demo
  name: ping-demo-balanced
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-demo
  template:
    metadata:
      labels:
        app: ping-demo
    spec:
      nodeSelector:
        cloud.google.com/compute-class: Balanced
        kubernetes.io/arch: amd64
      containers:
      - image: us-docker.pkg.dev/gke-demos-345619/compute-classes/ping-demo@sha256:8672d031d6a4146dbe3c7f18f11561ea5979a5e9e19efb1dabe4e08c23e2aef2
        name: ping-demo-balanced