apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ping-demo
  name: ping-demo-default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-demo
  template:
    metadata:
      labels:
        app: ping-demo
    spec:
      containers:
      - image: us-docker.pkg.dev/gke-demos-345619/compute-classes/ping-demo@sha256:8672d031d6a4146dbe3c7f18f11561ea5979a5e9e19efb1dabe4e08c23e2aef2
        name: ping-demo-default
        resources:
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
          limits:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi