apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ping-demo
  name: ping-demo-balanced
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-demo
  template:
    metadata:
      labels:
        app: ping-demo
    spec:
      nodeSelector:
        cloud.google.com/compute-class: Balanced
        kubernetes.io/arch: amd64
      containers:
      - image: us-docker.pkg.dev/gari-test/cloudonair/ping-demo:latest
        name: ping-demo-balanced