apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ping-demo
  name: ping-demo-arm64
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-demo
  template:
    metadata:
      labels:
        app: ping-demo
    spec:
      nodeSelector:
        cloud.google.com/compute-class: Scale-Out
        kubernetes.io/arch: arm64
      containers:
      - image: us-docker.pkg.dev/gke-demos-345619/compute-classes/ping-demo@sha256:906429f2af2834e53c0ca3876033045905cde60c19fff532bae457cb5f1e1e86
        name: ping-demo-arm64