apiVersion: "v1"
kind: "Service"
metadata:
  name: "tensorflow-service"
  labels:
    app: "tensorflow"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 8888
  selector:
    app: "tensorflow"
  type: "LoadBalancer"