apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tensorflow
  name: tensorflow-a100
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tensorflow
  template:
    metadata:
      labels:
        app: tensorflow
    spec:
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-a100
      containers:
      - image: tensorflow/tensorflow:latest-gpu-jupyter
        name: tensorflow-a100
        resources:
          limits:
            nvidia.com/gpu: 4